name: 'AWS Resources Deletion'
on:
  workflow_dispatch:

jobs:
  Terraform:
    name: 'Delete AWS Resources'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: setup/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform Destroy
        run:  terraform destroy -auto-approved
